<?php

namespace App\Services;

class SqlGeneratorService
{
    // Main entry point — receives the schema JSON array
    public function generate(array $schemaJson): string
    {
        $nodes = $schemaJson['nodes'] ?? [];
        $edges = $schemaJson['edges'] ?? [];

        if (empty($nodes)) {
            return '-- No tables found in schema.';
        }

        $lines = [];

        // Header comment
        $lines[] = '-- ================================================';
        $lines[] = '-- Generated by Schema-Genius';
        $lines[] = '-- Generated at: ' . now()->toDateTimeString();
        $lines[] = '-- ================================================';
        $lines[] = '';
        $lines[] = 'SET FOREIGN_KEY_CHECKS = 0;';
        $lines[] = '';

        // Generate each table
        foreach ($nodes as $node) {
            $tableSQL = $this->generateTable($node, $edges);
            $lines[]  = $tableSQL;
            $lines[]  = '';
        }

        // Generate pivot tables for N:N relationships
        $pivotSQL = $this->generatePivotTables($nodes, $edges);
        if ($pivotSQL) {
            $lines[] = $pivotSQL;
            $lines[] = '';
        }

        $lines[] = 'SET FOREIGN_KEY_CHECKS = 1;';

        return implode("\n", $lines);
    }

    // Generate a single CREATE TABLE statement
    private function generateTable(array $node, array $edges): string
    {
        $tableName = $this->sanitize($node['data']['name'] ?? 'unnamed_table');
        $columns   = $node['data']['columns'] ?? [];

        $lines   = [];
        $lines[] = "CREATE TABLE `{$tableName}` (";

        $columnLines  = [];
        $primaryKeys  = [];
        $uniqueKeys   = [];

        foreach ($columns as $col) {
            $colName = $this->sanitize($col['name'] ?? 'unnamed_column');
            $colSQL  = "  `{$colName}` " . $this->mapType($col);

            // NULL / NOT NULL
            $colSQL .= ($col['nullable'] ?? false) ? ' NULL' : ' NOT NULL';

            // Default value
            if (isset($col['default']) && $col['default'] !== null && $col['default'] !== '') {
                $default = $col['default'];
                // Wrap string defaults in quotes unless they are keywords
                $keywords = ['NULL', 'CURRENT_TIMESTAMP', 'NOW()', 'TRUE', 'FALSE'];
                if (!in_array(strtoupper($default), $keywords)) {
                    $default = "'{$default}'";
                }
                $colSQL .= " DEFAULT {$default}";
            }

            // Auto increment
            if ($col['autoIncrement'] ?? false) {
                $colSQL .= ' AUTO_INCREMENT';
            }

            $columnLines[] = $colSQL;

            // Track primary keys
            if ($col['pk'] ?? false) {
                $primaryKeys[] = "`{$colName}`";
            }

            // Track unique keys
            if (($col['unique'] ?? false) && !($col['pk'] ?? false)) {
                $uniqueKeys[] = $colName;
            }
        }

        // Add foreign key columns from edges
        foreach ($edges as $edge) {
            $relType = $edge['data']['relationshipType'] ?? $edge['label'] ?? '1:N';

            // Skip N:N — handled by pivot tables
            if ($relType === 'N:N') continue;

            // This table is the "many" side — add FK column
            if ($edge['target'] === $node['id']) {
                $sourceNode = null; // we don't have nodes here, handled in generateForeignKeys
            }
        }

        // Primary key constraint
        if (!empty($primaryKeys)) {
            $columnLines[] = '  PRIMARY KEY (' . implode(', ', $primaryKeys) . ')';
        }

        // Unique key constraints
        foreach ($uniqueKeys as $uq) {
            $columnLines[] = "  UNIQUE KEY `uq_{$tableName}_{$uq}` (`{$uq}`)";
        }

        $lines[] = implode(",\n", $columnLines);
        $lines[] = ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;";

        // Foreign key constraints (separate ALTER TABLE statements)
        $fkSQL = $this->generateForeignKeys($node, $edges);
        if ($fkSQL) {
            $lines[] = $fkSQL;
        }

        return implode("\n", $lines);
    }

    // Generate ALTER TABLE ... ADD FOREIGN KEY statements
    private function generateForeignKeys(array $node, array $edges): string
    {
        $tableName = $this->sanitize($node['data']['name'] ?? 'unnamed');
        $fkLines   = [];

        foreach ($edges as $edge) {
            $relType = $edge['data']['relationshipType'] ?? $edge['label'] ?? '1:N';

            // Skip N:N — handled separately
            if ($relType === 'N:N') continue;

            // This node is the target (many side) — it holds the FK
            if ($edge['target'] === $node['id']) {
                $sourceColumn = $this->sanitize(
                    ($edge['data']['sourceColumn'] ?? 'id')
                );
                $fkColumn     = $this->sanitize(
                    ($edge['data']['fkColumn'] ?? $tableName . '_id')
                );

                $fkLines[] = "ALTER TABLE `{$tableName}`";
                $fkLines[] = "  ADD COLUMN `{$fkColumn}` BIGINT UNSIGNED NOT NULL,";
                $fkLines[] = "  ADD CONSTRAINT `fk_{$tableName}_{$fkColumn}`";
                $fkLines[] = "  FOREIGN KEY (`{$fkColumn}`)";
                $fkLines[] = "  REFERENCES `" . $this->getNodeNameById($edge['source'], []) . "` (`{$sourceColumn}`)";
                $fkLines[] = "  ON DELETE CASCADE ON UPDATE CASCADE;";
                $fkLines[] = '';
            }
        }

        return implode("\n", $fkLines);
    }

    // Generate pivot tables for N:N relationships
    private function generatePivotTables(array $nodes, array $edges): string
    {
        $pivotLines = [];

        foreach ($edges as $edge) {
            $relType = $edge['data']['relationshipType'] ?? $edge['label'] ?? '';
            if ($relType !== 'N:N') continue;

            $sourceNode = $this->findNodeById($nodes, $edge['source']);
            $targetNode = $this->findNodeById($nodes, $edge['target']);

            if (!$sourceNode || !$targetNode) continue;

            $sourceName = $this->sanitize($sourceNode['data']['name']);
            $targetName = $this->sanitize($targetNode['data']['name']);
            $pivotName  = $sourceName . '_' . $targetName;

            $pivotLines[] = "CREATE TABLE `{$pivotName}` (";
            $pivotLines[] = "  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,";
            $pivotLines[] = "  `{$sourceName}_id` BIGINT UNSIGNED NOT NULL,";
            $pivotLines[] = "  `{$targetName}_id` BIGINT UNSIGNED NOT NULL,";
            $pivotLines[] = "  PRIMARY KEY (`id`),";
            $pivotLines[] = "  UNIQUE KEY `uq_{$pivotName}` (`{$sourceName}_id`, `{$targetName}_id`),";
            $pivotLines[] = "  FOREIGN KEY (`{$sourceName}_id`) REFERENCES `{$sourceName}` (`id`) ON DELETE CASCADE,";
            $pivotLines[] = "  FOREIGN KEY (`{$targetName}_id`) REFERENCES `{$targetName}` (`id`) ON DELETE CASCADE";
            $pivotLines[] = ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;";
            $pivotLines[] = '';
        }

        return implode("\n", $pivotLines);
    }

    // Map frontend column type to MySQL type
    private function mapType(array $col): string
    {
        $type   = strtoupper($col['type'] ?? 'VARCHAR');
        $length = $col['length'] ?? null;

        return match($type) {
            'VARCHAR'   => 'VARCHAR(' . ($length ?? 255) . ')',
            'BIGINT'    => 'BIGINT UNSIGNED',
            'INT'       => 'INT',
            'SMALLINT'  => 'SMALLINT',
            'TEXT'      => 'TEXT',
            'LONGTEXT'  => 'LONGTEXT',
            'BOOLEAN'   => 'TINYINT(1)',
            'DATE'      => 'DATE',
            'DATETIME'  => 'DATETIME',
            'TIMESTAMP' => 'TIMESTAMP',
            'DECIMAL'   => 'DECIMAL(' . ($length ?? '10,2') . ')',
            'FLOAT'     => 'FLOAT',
            'ENUM'      => 'ENUM(' . ($col['enumValues'] ?? "'active','inactive'") . ')',
            default     => 'VARCHAR(255)',
        };
    }

    // Remove dangerous characters from identifiers
    private function sanitize(string $name): string
    {
        // Replace spaces with underscores, remove special chars
        $name = preg_replace('/\s+/', '_', $name);
        $name = preg_replace('/[^a-zA-Z0-9_]/', '', $name);
        return strtolower($name) ?: 'unnamed';
    }

    private function findNodeById(array $nodes, string $id): ?array
    {
        foreach ($nodes as $node) {
            if ($node['id'] === $id) return $node;
        }
        return null;
    }

    private function getNodeNameById(string $id, array $nodes): string
    {
        $node = $this->findNodeById($nodes, $id);
        return $node ? $this->sanitize($node['data']['name']) : 'unknown_table';
    }
}