<?php

namespace App\Services;

class SqlGeneratorService
{
    private string $dialect  = 'mysql';
    private array  $allNodes = [];

    // ── Entry point ───────────────────────────────────────────────
    public function generate(array $schemaJson, string $dialect = 'mysql'): string
    {
        $this->dialect  = in_array($dialect, ['mysql', 'postgresql', 'sqlite']) ? $dialect : 'mysql';
        $nodes          = $schemaJson['nodes'] ?? [];
        $edges          = $schemaJson['edges'] ?? [];
        $this->allNodes = $nodes;

        if (empty($nodes)) {
            return '-- No tables found in schema.';
        }

        $lines = [];

        // ── Header ────────────────────────────────────────────────
        $dialectLabel = match($this->dialect) {
            'postgresql' => 'PostgreSQL',
            'sqlite'     => 'SQLite',
            default      => 'MySQL',
        };

        $lines[] = '-- ================================================';
        $lines[] = '-- Generated by Schema Genius';
        $lines[] = '-- Dialect : ' . $dialectLabel;
        $lines[] = '-- Generated at: ' . now()->toDateTimeString();
        $lines[] = '-- ================================================';
        $lines[] = '';

        // ── Dialect preamble ──────────────────────────────────────
        match($this->dialect) {
            'mysql'  => array_push($lines, 'SET FOREIGN_KEY_CHECKS = 0;', ''),
            'sqlite' => array_push($lines, 'PRAGMA foreign_keys = OFF;', ''),
            default  => null,
        };

        // ── Tables ────────────────────────────────────────────────
        foreach ($nodes as $node) {
            $lines[] = $this->generateTable($node, $edges);
            $lines[] = '';
        }

        // ── Pivot tables for M:N ──────────────────────────────────
        $pivot = $this->generatePivotTables($nodes, $edges);
        if ($pivot) {
            $lines[] = $pivot;
            $lines[] = '';
        }

        // ── MySQL: ALTER TABLE foreign keys (after all tables) ────
        if ($this->dialect === 'mysql') {
            foreach ($nodes as $node) {
                $fk = $this->generateMysqlForeignKeys($node, $edges);
                if ($fk) {
                    $lines[] = $fk;
                    $lines[] = '';
                }
            }
        }

        // ── Dialect postamble ─────────────────────────────────────
        match($this->dialect) {
            'mysql'  => array_push($lines, 'SET FOREIGN_KEY_CHECKS = 1;'),
            'sqlite' => array_push($lines, 'PRAGMA foreign_keys = ON;'),
            default  => null,
        };

        return implode("\n", $lines);
    }

    // ── Quote an identifier ───────────────────────────────────────
    private function q(string $name): string
    {
        return match($this->dialect) {
            'postgresql', 'sqlite' => '"' . $name . '"',
            default                => '`' . $name . '`',
        };
    }

    // ── Map column type per dialect ───────────────────────────────
    private function mapType(array $col): string
    {
        $type      = strtoupper($col['type'] ?? 'VARCHAR');
        $length    = $col['length'] ?? null;
        $isAutoInc = $col['autoIncrement'] ?? false;

        return match($this->dialect) {
            'postgresql' => match($type) {
                'BIGINT'    => $isAutoInc ? 'BIGSERIAL' : 'BIGINT',
                'INT'       => $isAutoInc ? 'SERIAL'    : 'INTEGER',
                'SMALLINT'  => $isAutoInc ? 'SMALLSERIAL' : 'SMALLINT',
                'VARCHAR'   => 'VARCHAR(' . ($length ?? 255) . ')',
                'TEXT'      => 'TEXT',
                'LONGTEXT'  => 'TEXT',
                'BOOLEAN'   => 'BOOLEAN',
                'DATE'      => 'DATE',
                'DATETIME'  => 'TIMESTAMP',
                'TIMESTAMP' => 'TIMESTAMP',
                'DECIMAL'   => 'NUMERIC(' . ($length ?? '10,2') . ')',
                'FLOAT'     => 'REAL',
                'ENUM'      => 'VARCHAR(50)',
                default     => 'VARCHAR(255)',
            },
            'sqlite' => match($type) {
                'BIGINT', 'INT', 'SMALLINT' => 'INTEGER',
                'VARCHAR'                   => 'TEXT',
                'TEXT', 'LONGTEXT'          => 'TEXT',
                'BOOLEAN'                   => 'INTEGER',
                'DATE', 'DATETIME', 'TIMESTAMP' => 'TEXT',
                'DECIMAL', 'FLOAT'          => 'REAL',
                'ENUM'                      => 'TEXT',
                default                     => 'TEXT',
            },
            default => match($type) {
                'VARCHAR'   => 'VARCHAR(' . ($length ?? 255) . ')',
                'BIGINT'    => 'BIGINT UNSIGNED',
                'INT'       => 'INT',
                'SMALLINT'  => 'SMALLINT',
                'TEXT'      => 'TEXT',
                'LONGTEXT'  => 'LONGTEXT',
                'BOOLEAN'   => 'TINYINT(1)',
                'DATE'      => 'DATE',
                'DATETIME'  => 'DATETIME',
                'TIMESTAMP' => 'TIMESTAMP',
                'DECIMAL'   => 'DECIMAL(' . ($length ?? '10,2') . ')',
                'FLOAT'     => 'FLOAT',
                'ENUM'      => 'ENUM(' . ($col['enumValues'] ?? "'active','inactive'") . ')',
                default     => 'VARCHAR(255)',
            },
        };
    }

    // ── CREATE TABLE ──────────────────────────────────────────────
    private function generateTable(array $node, array $edges): string
    {
        $tableName   = $this->sanitize($node['data']['name'] ?? 'unnamed_table');
        $columns     = $node['data']['columns'] ?? [];
        $columnLines = [];
        $primaryKeys = [];
        $uniqueKeys  = [];

        foreach ($columns as $col) {
            $colName   = $this->sanitize($col['name'] ?? 'unnamed_column');
            $isAutoInc = $col['autoIncrement'] ?? false;
            $isPk      = $col['pk'] ?? false;

            // SQLite: INTEGER PRIMARY KEY AUTOINCREMENT must be inline
            if ($this->dialect === 'sqlite' && $isPk && $isAutoInc) {
                $columnLines[] = '  ' . $this->q($colName) . ' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT';
                continue;
            }

            $colSQL = '  ' . $this->q($colName) . ' ' . $this->mapType($col);
            $colSQL .= ($col['nullable'] ?? false) ? ' NULL' : ' NOT NULL';

            if (isset($col['default']) && $col['default'] !== null && $col['default'] !== '') {
                $default  = $col['default'];
                $keywords = ['NULL', 'CURRENT_TIMESTAMP', 'NOW()', 'TRUE', 'FALSE'];
                if (!in_array(strtoupper($default), $keywords)) {
                    $default = "'{$default}'";
                }
                $colSQL .= " DEFAULT {$default}";
            }

            if ($isAutoInc && $this->dialect === 'mysql') {
                $colSQL .= ' AUTO_INCREMENT';
            }

            $columnLines[] = $colSQL;

            if ($isPk) {
                $primaryKeys[] = $this->q($colName);
            }
            if (($col['unique'] ?? false) && !$isPk) {
                $uniqueKeys[] = $colName;
            }
        }

        // PRIMARY KEY
        if (!empty($primaryKeys)) {
            $columnLines[] = '  PRIMARY KEY (' . implode(', ', $primaryKeys) . ')';
        }

        // UNIQUE constraints
        foreach ($uniqueKeys as $uq) {
            if ($this->dialect === 'mysql') {
                $columnLines[] = "  UNIQUE KEY " . $this->q("uq_{$tableName}_{$uq}") . " (" . $this->q($uq) . ")";
            } else {
                $columnLines[] = "  CONSTRAINT " . $this->q("uq_{$tableName}_{$uq}") . " UNIQUE (" . $this->q($uq) . ")";
            }
        }

        // PostgreSQL / SQLite: inline FK constraints
        if (in_array($this->dialect, ['postgresql', 'sqlite'])) {
            foreach ($this->buildInlineFks($node, $edges) as $fk) {
                $columnLines[] = $fk;
            }
        }

        $closing = $this->dialect === 'mysql'
            ? ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;"
            : ");";

        return "CREATE TABLE " . $this->q($tableName) . " (\n"
            . implode(",\n", $columnLines) . "\n"
            . $closing;
    }

    // ── Inline FK for PostgreSQL / SQLite ─────────────────────────
    private function buildInlineFks(array $node, array $edges): array
    {
        $tableName = $this->sanitize($node['data']['name'] ?? 'unnamed');
        $fkLines   = [];

        foreach ($edges as $edge) {
            $relType = $edge['data']['type'] ?? $edge['data']['relationshipType'] ?? '1:N';
            if (in_array($relType, ['N:N', 'M:N'])) continue;
            if ($edge['target'] !== $node['id']) continue;

            $sourceNode   = $this->findNodeById($this->allNodes, $edge['source']);
            $sourceTable  = $sourceNode ? $this->sanitize($sourceNode['data']['name']) : 'unknown_table';
            $sourceColumn = $this->sanitize($edge['data']['sourceColumn'] ?? 'id');
            $fkColumn     = $this->sanitize($edge['data']['fkColumn'] ?? $sourceTable . '_id');

            $fkLines[] = "  CONSTRAINT " . $this->q("fk_{$tableName}_{$fkColumn}")
                . " FOREIGN KEY (" . $this->q($fkColumn) . ")"
                . " REFERENCES " . $this->q($sourceTable) . " (" . $this->q($sourceColumn) . ")"
                . " ON DELETE CASCADE ON UPDATE CASCADE";
        }

        return $fkLines;
    }

    // ── MySQL ALTER TABLE FKs (separate statements) ───────────────
    private function generateMysqlForeignKeys(array $node, array $edges): string
    {
        $tableName = $this->sanitize($node['data']['name'] ?? 'unnamed');
        $fkLines   = [];

        foreach ($edges as $edge) {
            $relType = $edge['data']['type'] ?? $edge['data']['relationshipType'] ?? '1:N';
            if (in_array($relType, ['N:N', 'M:N'])) continue;
            if ($edge['target'] !== $node['id']) continue;

            $sourceNode   = $this->findNodeById($this->allNodes, $edge['source']);
            $sourceTable  = $sourceNode ? $this->sanitize($sourceNode['data']['name']) : 'unknown_table';
            $sourceColumn = $this->sanitize($edge['data']['sourceColumn'] ?? 'id');
            $fkColumn     = $this->sanitize($edge['data']['fkColumn'] ?? $sourceTable . '_id');

            $fkLines[] = "ALTER TABLE `{$tableName}`";
            $fkLines[] = "  ADD COLUMN `{$fkColumn}` BIGINT UNSIGNED NOT NULL,";
            $fkLines[] = "  ADD CONSTRAINT `fk_{$tableName}_{$fkColumn}`";
            $fkLines[] = "  FOREIGN KEY (`{$fkColumn}`)";
            $fkLines[] = "  REFERENCES `{$sourceTable}` (`{$sourceColumn}`)";
            $fkLines[] = "  ON DELETE CASCADE ON UPDATE CASCADE;";
            $fkLines[] = '';
        }

        return implode("\n", $fkLines);
    }

    // ── Pivot / junction tables for M:N ───────────────────────────
    private function generatePivotTables(array $nodes, array $edges): string
    {
        $pivotLines = [];

        foreach ($edges as $edge) {
            $relType = $edge['data']['type'] ?? $edge['data']['relationshipType'] ?? '';
            if (!in_array($relType, ['N:N', 'M:N'])) continue;

            $sourceNode = $this->findNodeById($nodes, $edge['source']);
            $targetNode = $this->findNodeById($nodes, $edge['target']);
            if (!$sourceNode || !$targetNode) continue;

            $src   = $this->sanitize($sourceNode['data']['name']);
            $tgt   = $this->sanitize($targetNode['data']['name']);
            $pivot = $src . '_' . $tgt;
            $q     = fn($n) => $this->q($n);

            if ($this->dialect === 'mysql') {
                $pivotLines[] = "CREATE TABLE `{$pivot}` (";
                $pivotLines[] = "  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,";
                $pivotLines[] = "  `{$src}_id` BIGINT UNSIGNED NOT NULL,";
                $pivotLines[] = "  `{$tgt}_id` BIGINT UNSIGNED NOT NULL,";
                $pivotLines[] = "  PRIMARY KEY (`id`),";
                $pivotLines[] = "  UNIQUE KEY `uq_{$pivot}` (`{$src}_id`, `{$tgt}_id`),";
                $pivotLines[] = "  FOREIGN KEY (`{$src}_id`) REFERENCES `{$src}` (`id`) ON DELETE CASCADE,";
                $pivotLines[] = "  FOREIGN KEY (`{$tgt}_id`) REFERENCES `{$tgt}` (`id`) ON DELETE CASCADE";
                $pivotLines[] = ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;";
            } elseif ($this->dialect === 'postgresql') {
                $pivotLines[] = "CREATE TABLE {$q($pivot)} (";
                $pivotLines[] = "  {$q('id')} BIGSERIAL NOT NULL,";
                $pivotLines[] = "  {$q($src.'_id')} BIGINT NOT NULL,";
                $pivotLines[] = "  {$q($tgt.'_id')} BIGINT NOT NULL,";
                $pivotLines[] = "  PRIMARY KEY ({$q('id')}),";
                $pivotLines[] = "  CONSTRAINT {$q('uq_'.$pivot)} UNIQUE ({$q($src.'_id')}, {$q($tgt.'_id')}),";
                $pivotLines[] = "  CONSTRAINT {$q('fk_'.$pivot.'_'.$src)} FOREIGN KEY ({$q($src.'_id')}) REFERENCES {$q($src)} ({$q('id')}) ON DELETE CASCADE,";
                $pivotLines[] = "  CONSTRAINT {$q('fk_'.$pivot.'_'.$tgt)} FOREIGN KEY ({$q($tgt.'_id')}) REFERENCES {$q($tgt)} ({$q('id')}) ON DELETE CASCADE";
                $pivotLines[] = ");";
            } else {
                $pivotLines[] = "CREATE TABLE {$q($pivot)} (";
                $pivotLines[] = "  {$q('id')} INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,";
                $pivotLines[] = "  {$q($src.'_id')} INTEGER NOT NULL,";
                $pivotLines[] = "  {$q($tgt.'_id')} INTEGER NOT NULL,";
                $pivotLines[] = "  CONSTRAINT {$q('uq_'.$pivot)} UNIQUE ({$q($src.'_id')}, {$q($tgt.'_id')}),";
                $pivotLines[] = "  FOREIGN KEY ({$q($src.'_id')}) REFERENCES {$q($src)} ({$q('id')}) ON DELETE CASCADE,";
                $pivotLines[] = "  FOREIGN KEY ({$q($tgt.'_id')}) REFERENCES {$q($tgt)} ({$q('id')}) ON DELETE CASCADE";
                $pivotLines[] = ");";
            }

            $pivotLines[] = '';
        }

        return implode("\n", $pivotLines);
    }

    // ── Helpers ───────────────────────────────────────────────────
    private function sanitize(string $name): string
    {
        $name = preg_replace('/\s+/', '_', $name);
        $name = preg_replace('/[^a-zA-Z0-9_]/', '', $name);
        return strtolower($name) ?: 'unnamed';
    }

    private function findNodeById(array $nodes, string $id): ?array
    {
        foreach ($nodes as $node) {
            if ($node['id'] === $id) return $node;
        }
        return null;
    }
}
